# version: "3.8"
# services:
#   zookeeper:
#     image: bitnami/zookeeper:3
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#     ports:
#       - "2181:2181"

#   kafka:
#     image: bitnami/kafka:3.6.1
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#       - KAFKA_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#       - ALLOW_PLAINTEXT_LISTENER=yes
#     depends_on:
#       - zookeeper
#     ports:
#       - "9092:9092"

#   postgres:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: quicksale
#       POSTGRES_PASSWORD: quicksale
#       POSTGRES_DB: quicksale
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:7
#     ports:
#       - "6379:6379"

#   auth-service:
#     build: ./services/auth-service
#     environment:
#       - DATABASE_URL=postgresql://quicksale:quicksale@postgres:5432/quicksale
#       - JWT_SECRET=change_this_secret
#       - PORT=4001
#     ports:
#       - "4001:4001"
#     depends_on:
#       - postgres

#   catalog-service:
#     build: ./services/catalog-service
#     environment:
#       - DATABASE_URL=postgresql://quicksale:quicksale@postgres:5432/quicksale
#       - KAFKA_BROKERS=kafka:9092
#       - PORT=4002
#     ports:
#       - "4002:4002"
#     depends_on:
#       - postgres
#       - kafka

#   order-service:
#     build: ./services/order-service
#     environment:
#       - DATABASE_URL=postgresql://quicksale:quicksale@postgres:5432/quicksale
#       - KAFKA_BROKERS=kafka:9092
#       - PORT=4003
#     ports:
#       - "4003:4003"
#     depends_on:
#       - postgres
#       - kafka

#   notifier-service:
#     build: ./services/notifier-service
#     environment:
#       - KAFKA_BROKERS=kafka:9092
#       - JWT_SECRET=change_this_secret
#       - PORT=4004
#     ports:
#       - "4004:4004"
#     depends_on:
#       - kafka

#   api-gateway:
#     build: ./services/api-gateway
#     environment:
#       - PORT=8080
#       - JWT_SECRET=change_this_secret
#       - AUTH_URL=http://auth-service:4001
#       - CATALOG_URL=http://catalog-service:4002
#       - ORDER_URL=http://order-service:4003
#     ports:
#       - "8080:8080"
#     depends_on:
#       - auth-service
#       - catalog-service
#       - order-service

# volumes:
#   pgdata:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: quicksale
      POSTGRES_PASSWORD: quicksale
      POSTGRES_DB: quicksale
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth-service:
    build: ./services/auth-service
    environment:
      - DATABASE_URL=postgresql://quicksale:quicksale@postgres:5432/quicksale
      - JWT_SECRET=change_this_secret
      - PORT=4001
    ports:
      - "4001:4001"
    depends_on:
      - postgres

  catalog-service:
    build: ./services/catalog-service
    environment:
      - DATABASE_URL=postgresql://quicksale:quicksale@postgres:5432/quicksale
      - KAFKA_BROKERS=kafka:9092
      - PORT=4002
    ports:
      - "4002:4002"
    depends_on:
      - postgres
      - kafka

  order-service:
    build: ./services/order-service
    environment:
      - DATABASE_URL=postgresql://quicksale:quicksale@postgres:5432/quicksale
      - KAFKA_BROKERS=kafka:9092
      - PORT=4003
    ports:
      - "4003:4003"
    depends_on:
      - postgres
      - kafka

  notifier-service:
    build: ./services/notifier-service
    environment:
      - KAFKA_BROKERS=kafka:9092
      - JWT_SECRET=change_this_secret
      - PORT=4004
    ports:
      - "4004:4004"
    depends_on:
      - kafka

  api-gateway:
    build: ./services/api-gateway
    environment:
      - PORT=8080
      - JWT_SECRET=change_this_secret
      - AUTH_URL=http://auth-service:4001
      - CATALOG_URL=http://catalog-service:4002
      - ORDER_URL=http://order-service:4003
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - catalog-service
      - order-service

volumes:
  pgdata:
